### ISSUE TITLE
atomic storage modify --driver overlay2 is broken.

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/atomic#911] opened 2017-02-24 13:16 UTC
Bug 1:

This should not fail:

```
# atomic storage modify --driver overlay2
[Errno 2] No such file or directory: '/etc/sysconfig/docker-storage-setup'
```

We should create the file if it does not exist.

```
# touch /etc/sysconfig/docker-storage-setup
# atomic --debug storage modify --driver overlay2
```
Works

Bug #2

```
# systemctl stop docker
# atomic storage modify --driver overlay2
The docker daemon does not appear to be running.
```

Docker damon should not be required to run to modify config.

Bug #3 

```
# atomic storage modify --driver <tab><tab> 
devicemapper  overlay      
```

Overlay2 should be a valid option in bash completions.

**Comment by rhatdan** [comment] 2017-02-24 13:16
@shishir-a412ed can you fix this up?

**Comment by shishir-a412ed** [comment] 2017-02-26 05:40
@rhatdan 
Bug 1:

I am wondering what would be the case: where `/etc/sysconfig/docker-storage-setup` does not exist ? Since we ship this file as part of rpm. It should always exist unless a user accidentally deletes it.
Now if a user accidentally deletes a version of `/etc/sysconfig/docker-storage-setup` which had some configuration options e.g. `DEVS="/dev/vdb"`. Should we just recreate a new file ? ignoring the previous accidental delete ?  

@rhvgoyal WDYT about Bug 1 ? Should we just create the file if it does not exist ? 

Bug 2: I also faced this issue and a few more when I was testing `atomic storage modify`  and `atomic storage reset` on thursday. I was on PTO on Friday, so couldn't continue digging deeper.

The problem is somewhere in the code (both for modify and reset), `NoDockerDaemon` exception is thrown which is not needed here. I found a few other problems.

    a) Problem in `atomic storage reset`: 
         Case 1) When docker daemon is not running (systemctl stop docker).
                       `atomic storage reset` would throw the `NoDockerDaemon` exception as I pointed out above and you will get the error message `The docker daemon does not appear to be running`.
         Case 2) systemctl start docker.
                       `atomic storage reset` would now throw an error saying `Docker daemon must be stopped before resetting storage`. I believe this condition was added later here.
https://github.com/projectatomic/atomic/blob/master/Atomic/storage.py#L151

       Since Case(1) and Case (2) are mutually exclusive, I can never reset my storage. Whether I start or stop docker daemon I will run into one of these error cases.

    b) Another problem is `atomic storage modify` should just be updating the config file (`/etc/sysconfig/docker-storage-setup`). However right now it is calling `/usr/bin/docker-storage-setup` (Which I believe we discussed, and you mentioned that it does not call docker-storage-setup).

Specifically this piece of code is baffling me. 
https://github.com/projectatomic/atomic/blob/master/Atomic/storage.py#L193-L200

Where we call `docker-storage-setup` on `L194` (which we should not) and then if there is an exception, We are calling `docker-storage-setup` again on `L199`. Not sure what was the rationale behind this.

Bug 3: Opening a PR for this.

I will try to fix these issue on Monday.

Shishir

**Comment by shishir-a412ed** [comment] 2017-02-26 17:58
PR: https://github.com/projectatomic/atomic/pull/914 for Bug 3.

Shishir

**Comment by rhatdan** [comment] 2017-02-27 12:39
Yes I think we should create it if it does not exist.  Does docker-storage-setup/container-storage-setup work properly without a configuration file?

Bug 2 you need to remove the conflict.  Talk to @baude to see what he wants to do?

**Comment by shishir-a412ed** [comment] 2017-03-01 16:17
#921 fixes bug # 2. Opening a PR for bug # 1 now.

Shishir

**Comment by shishir-a412ed** [comment] 2017-03-01 22:05
#924 fixed Bug # 1. I think we can close this issue now.
All the 3 bugs are fixed.

ping @rhatdan 

Shishir

**Closed** 2017-03-02 14:38 UTC
