### ISSUE TITLE
Change polkit policy to `<allow_any>auth_admin</>`

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/atomic#450] opened 2016-07-05 13:43 UTC
Right now we authorize things like `StorageReset` under `org.atomic.read` which is wrong.

Second, for some reason at least with the Cockpit session we had to change `<allow_any>yes</>` when (as far as I understand) the Cockpit session should be under `<allow_active>`).

**Comment by mvollmer** [comment] 2016-07-05 14:06
As far as I understand, `allow_active` and `allow_inactive` only apply to local sessions, like the console and gdm, but not remote sessions like ssh and Cockpit.  So the problem is that the Cockpit sessions are remote, not that they are inactive.

`<allow_any>auth_admin</allow_any>` might be what you want.

**Comment by cgwalters** [comment] 2016-07-05 14:39
Has Cockpit been changing other services similarly?  Looks like it's likely, `org.freedesktop.NetworkManager.network-control` has `<allow_any>auth_admin</allow_any>` too.

**Comment by rhatdan** [comment] 2016-07-06 13:58
I agree these settings are bad.  Since the primary use case for these bindings is intended to be cockpit, we need to satisfy its use case.

**Comment by rhatdan** [comment] 2016-08-16 16:00
FIxed in master

**Closed by rhatdan** 2016-08-16 16:00 UTC
