### ISSUE TITLE
Atomic should give appropriate error message if docker isn't running:

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/atomic#205] opened 2015-11-11 19:35 UTC
Atomic should give appropriate error message if docker isn't running:

```
[root@localhost ~]# atomic info projectatomic/helloapache
('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

Running `strace` shows me this: 

```
connect(4, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, 22) = -1 ENOENT (No such file or directory)
write(2, "('Connection aborted.', FileNotF"..., 75('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

Tested with rpm from here: https://kojipkgs.fedoraproject.org//work/tasks/6485/11796485/atomic-1.6-5.git09ac479.fc23.x86_64.rpm

**Comment by rhatdan** [comment] 2015-11-11 19:39
What do you want to see?  

We could enhance the message to say something 
"Unable to connect to docker, No such file or directory"

The problem is we are calling into docker-python and this is the exception that it is raising.

**Comment by dustymabe** [comment] 2015-11-11 19:47
I see. 

Yes your message gets us much more information than what we get now (i.e. with your message we now know it is an issue with docker). Expanding on your message something like the following might be best: 

"Unable to connect to docker via /var/run/docker.sock: No such file or directory"

Thoughts?

**Comment by rhatdan** [comment] 2015-11-11 20:10
Problem is I don't know that /var/run/docker.sock is the mechanism for you to connect to docker.  You could have set it up to listen elsewhere or on  the network.

**Comment by dustymabe** [comment] 2015-11-11 20:26
Yeah your first message was good enough. One question though:

Does atomic allow you to configure what remote you connect to right now? Or is it something that is globally configured somehow? 

Atomic CLI just calls `docker.Client()` right [now](https://github.com/projectatomic/atomic/blob/master/Atomic/atomic.py#L90) with no args so could we reasonably say we know what it is going to try to connect to?

Even if we didn't know we could inspect the base_url from the object:

```
>>> import docker
>>> cli = docker.Client() 
>>> cli.base_url
'http+docker://localunixsocket'
```

**Comment by rhatdan** [comment] 2015-11-11 20:28
Sure but that would like an ugly message for the user.

We don't want to override the default since we are execing docker client in a few cases still.

**Comment by dustymabe** [comment] 2015-11-11 20:31
ok cool your original suggestion in this thread works. let's go with that.

**Comment by rhatdan** [comment] 2015-11-11 20:41
Take a look at https://github.com/projectatomic/atomic/pull/206 and give me feedback.

**Comment by rhatdan** [comment] 2015-11-13 19:07
206 is merged

**Closed by rhatdan** 2015-11-13 19:07 UTC
