### ISSUE TITLE
Cannot build atomic from source

### ISSUE THREAD

**Issue by dharmit** [projectatomic/atomic#409] opened 2016-06-06 10:08 UTC
Hi, 

I'm getting similar error on both Fedora 23 and CentOS 7.2 when I try to build atomic:

CentOS 7.2
~~~
# make
/usr/bin/python setup.py build
running build
running build_py
running build_scripts
/usr/bin/pylint -E --additional-builtins=_ *.py atomic Atomic tests/unit/*.py
No config file found, using default configuration
************* Module Atomic.atomic
E: 20, 8: No name 'OSTree' in module 'gi.repository' (no-name-in-module)
make: *** [pylint-check] Error 2
~~~

Fedora 23
~~~
$ make
/usr/bin/python setup.py build
running build
running build_py
running build_scripts
/usr/bin/pylint -E --additional-builtins=_ *.py atomic Atomic tests/unit/*.py
No config file found, using default configuration
************* Module Atomic.atomic
E: 20, 8: No name 'OSTree' in module 'gi.repository' (no-name-in-module)
Makefile:28: recipe for target 'pylint-check' failed
make: *** [pylint-check] Error 2
~~~

**Comment by giuseppe** [comment] 2016-06-06 13:57
what version are you using?  This should be already fixed on git by https://github.com/projectatomic/atomic/commit/02fe5ce47ac27886c1e92677a47c981f200a7380

**Comment by dharmit** [comment] 2016-06-06 14:04
@giuseppe I cloned the repo and tried building. So I'm building off the master branch. IIUC the commit you referred to is merged in to the master.

**Comment by miabbott** [comment] 2016-06-06 14:14
I just tried building `atomic` in a F23 container and was not able to reproduce this.

```
[root@de73832c107d atomic]# git clone https://github.com/projectatomic/atomic.git
Cloning into 'atomic'...
remote: Counting objects: 2738, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 2738 (delta 22), reused 0 (delta 0), pack-reused 2688
Receiving objects: 100% (2738/2738), 1.58 MiB | 1.01 MiB/s, done.
Resolving deltas: 100% (1780/1780), done.
Checking connectivity... done.
[root@de73832c107d ~]# cd atomic/
[root@de73832c107d atomic]# git rev-parse HEAD
e6cc1db8a0a760e38cb2bf41d67b970a00743ecb
[root@de73832c107d atomic]# make
/usr/bin/python setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/Atomic
copying Atomic/Export.py -> build/lib/Atomic
copying Atomic/storage.py -> build/lib/Atomic
copying Atomic/client.py -> build/lib/Atomic
copying Atomic/verify.py -> build/lib/Atomic
copying Atomic/util.py -> build/lib/Atomic
copying Atomic/__init__.py -> build/lib/Atomic
copying Atomic/run.py -> build/lib/Atomic
copying Atomic/atomic.py -> build/lib/Atomic
copying Atomic/help.py -> build/lib/Atomic
copying Atomic/diff.py -> build/lib/Atomic
copying Atomic/scan.py -> build/lib/Atomic
copying Atomic/Import.py -> build/lib/Atomic
copying Atomic/pulp.py -> build/lib/Atomic
copying Atomic/satellite.py -> build/lib/Atomic
copying Atomic/top.py -> build/lib/Atomic
copying Atomic/mount.py -> build/lib/Atomic
running build_scripts
creating build/scripts-2.7
copying and adjusting atomic -> build/scripts-2.7
copying and adjusting atomic_dbus.py -> build/scripts-2.7
changing mode of build/scripts-2.7/atomic from 644 to 755
changing mode of build/scripts-2.7/atomic_dbus.py from 644 to 755
/usr/bin/go-md2man -in docs/atomic-diff.1.md -out docs/atomic-diff.1.tmp && touch docs/atomic-diff.1.tmp && mv docs/atomic-diff.1.tmp docs/atomic-diff.1
/usr/bin/go-md2man -in docs/atomic-install.1.md -out docs/atomic-install.1.tmp && touch docs/atomic-install.1.tmp && mv docs/atomic-install.1.tmp docs/atomic-install.1
/usr/bin/go-md2man -in docs/atomic-stop.1.md -out docs/atomic-stop.1.tmp && touch docs/atomic-stop.1.tmp && mv docs/atomic-stop.1.tmp docs/atomic-stop.1
/usr/bin/go-md2man -in docs/atomic.1.md -out docs/atomic.1.tmp && touch docs/atomic.1.tmp && mv docs/atomic.1.tmp docs/atomic.1
/usr/bin/go-md2man -in docs/atomic-uninstall.1.md -out docs/atomic-uninstall.1.tmp && touch docs/atomic-uninstall.1.tmp && mv docs/atomic-uninstall.1.tmp docs/atomic-uninstall.1
/usr/bin/go-md2man -in docs/atomic-run.1.md -out docs/atomic-run.1.tmp && touch docs/atomic-run.1.tmp && mv docs/atomic-run.1.tmp docs/atomic-run.1
/usr/bin/go-md2man -in docs/atomic-version.1.md -out docs/atomic-version.1.tmp && touch docs/atomic-version.1.tmp && mv docs/atomic-version.1.tmp docs/atomic-version.1
/usr/bin/go-md2man -in docs/atomic-update.1.md -out docs/atomic-update.1.tmp && touch docs/atomic-update.1.tmp && mv docs/atomic-update.1.tmp docs/atomic-update.1
/usr/bin/go-md2man -in docs/atomic-help.1.md -out docs/atomic-help.1.tmp && touch docs/atomic-help.1.tmp && mv docs/atomic-help.1.tmp docs/atomic-help.1
/usr/bin/go-md2man -in docs/atomic-images.1.md -out docs/atomic-images.1.tmp && touch docs/atomic-images.1.tmp && mv docs/atomic-images.1.tmp docs/atomic-images.1
/usr/bin/go-md2man -in docs/atomic-unmount.1.md -out docs/atomic-unmount.1.tmp && touch docs/atomic-unmount.1.tmp && mv docs/atomic-unmount.1.tmp docs/atomic-unmount.1
/usr/bin/go-md2man -in docs/atomic-info.1.md -out docs/atomic-info.1.tmp && touch docs/atomic-info.1.tmp && mv docs/atomic-info.1.tmp docs/atomic-info.1
/usr/bin/go-md2man -in docs/atomic-push.1.md -out docs/atomic-push.1.tmp && touch docs/atomic-push.1.tmp && mv docs/atomic-push.1.tmp docs/atomic-push.1
/usr/bin/go-md2man -in docs/atomic-verify.1.md -out docs/atomic-verify.1.tmp && touch docs/atomic-verify.1.tmp && mv docs/atomic-verify.1.tmp docs/atomic-verify.1
/usr/bin/go-md2man -in docs/atomic-scan.1.md -out docs/atomic-scan.1.tmp && touch docs/atomic-scan.1.tmp && mv docs/atomic-scan.1.tmp docs/atomic-scan.1
/usr/bin/go-md2man -in docs/atomic-mount.1.md -out docs/atomic-mount.1.tmp && touch docs/atomic-mount.1.tmp && mv docs/atomic-mount.1.tmp docs/atomic-mount.1
/usr/bin/go-md2man -in docs/atomic-top.1.md -out docs/atomic-top.1.tmp && touch docs/atomic-top.1.tmp && mv docs/atomic-top.1.tmp docs/atomic-top.1
/usr/bin/go-md2man -in docs/atomic-pull.1.md -out docs/atomic-pull.1.tmp && touch docs/atomic-pull.1.tmp && mv docs/atomic-pull.1.tmp docs/atomic-pull.1
/usr/bin/go-md2man -in docs/atomic-host.1.md -out docs/atomic-host.1.tmp && touch docs/atomic-host.1.tmp && mv docs/atomic-host.1.tmp docs/atomic-host.1
/usr/bin/go-md2man -in docs/atomic-storage.1.md -out docs/atomic-storage.1.tmp && touch docs/atomic-storage.1.tmp && mv docs/atomic-storage.1.tmp docs/atomic-storage.1
/usr/bin/pylint -E --additional-builtins=_ *.py atomic Atomic tests/unit/*.py
No config file found, using default configuration
/usr/bin/go build dockertar-sha256-helper.go
# command-line-arguments
ar: `u' modifier ignored since `D' is the default (see `U')
```

**Comment by giuseppe** [comment] 2016-06-06 14:22
@dharmit could you please try this patch?

diff --git a/Atomic/atomic.py b/Atomic/atomic.py
index e695a16..da640ee 100644
--- a/Atomic/atomic.py
+++ b/Atomic/atomic.py
@@ -18,7 +18,7 @@ try:
     import gi
     try:
         gi.require_version('OSTree', '1.0')
-        from gi.repository import Gio, GLib, OSTree
+        from gi.repository import Gio, GLib, OSTree # pylint: disable=no-name-in-module
         OSTREE_PRESENT = True
     except ValueError:
         OSTREE_PRESENT = False

**Comment by miabbott** [comment] 2016-06-06 15:17
Interestingly, performing a similar test using a CentOS container fails as originally described.

But the patch from @giuseppe does appear to fix the issue.

**Comment by giuseppe** [comment] 2016-06-06 15:20
PR here: https://github.com/projectatomic/atomic/pull/412

**Closed** 2016-06-06 15:41 UTC
